### ISSUE TITLE
Commits that should be picked from tmp branch

### ISSUE THREAD

**Issue by jyoppomu** [aYukiYoshida/GIKYOKU#1]
- [x] Rewrite package infomation: #4 
    - bf2a46f19f80ccb7475405fd9e8e5ff52e86b713
    - 2819730cfdfaaf3c6471a20122a8f1952778b7c4
- [x] Restructure environment of development: #5
    - [x] Ignore scripts/release.js when linting: f11e475235c9243c339a0aa3794fa67f991f1d95
    - [x] Modify GitHub Actions workflow: 288266d30bd26539898610cb61f5a092bb85f418
    - [x] Fix tests: d17e55986aa0d088de26743ee339f939f8040c48
- [x] Add method to validate if selector is editable or not: #3 #7
    - 3eed840a24d036aa2625832f24e495e51eed7e93
    - 393b3015cebac2de5a1bf74aacb5de0b29e8657b
- [x] Implement question of Screen #9
    - b744b5eb71cb7192da49b9c71dab6a9958574b1b

**Comment by jyoppomu** [comment]
This issue is solved, because all task have been finish.
